version: "3"

services:

  gdx-proxy-server:
    image: "ramesesinc/gdx-proxy-server:v001"
    container_name: gdx-proxy-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    environment:
      TZ: "Asia/Manila"
    ports:
      - "8500:80"


  gdx-client:
    image: "ramesesinc/gdx-client:1.01.003"
    container_name: gdx-client
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ../_custom/env.conf
    ports:
      - "8571:8571"
    volumes:
      - ../_res/connections:/apps/gdx/connections/ext
