version: "3"

services:
  
  queue-proxy:
    image: nginx:latest
    container_name: queue-proxy
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    links:
      - queue-server
    environment:
      TZ: "Asia/Manila"
    ports:
      - "9999:9999"
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./custom:/resources


  queue-server:
    image: ramesesinc/queue-server:255.02.002
    container_name: queue-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ../_custom/env.conf
    ports:
      - "9980:8080"
      - "9970:8070"
      - "9960:8060"
    volumes:
      - ./custom/images/lgu-logo.png:/webroot/res/images/lgu-logo.png
