version: "3"

services:
  
  queue-proxy:
    image: nginx:latest
    container_name: queue-proxy
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    links:
      - queue-server
    environment:
      TZ: "Asia/Manila"
    ports:
      - "9999:9999"
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./resources:/resources


  queue-server:
    image: ramesesinc/queue-server:255.01.003
    container_name: queue-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ./videos.conf
    ports:
      - "9980:8080"
      - "9970:8070"
    volumes:
      - ./resources/images/lgu-logo.png:/apps/server/web/monitor.queue/res/images/lgu-logo.png
      - ./resources/css:/apps/server/web/monitor.queue/themes/default/css
      - ./resources/files/queue.pg:/apps/server/web/monitor.queue/files/queue.pg
      - ./resources/files/queueing.pg:/apps/server/web/monitor.queue/files/queueing.pg
      - ./resources/files/queuenumber.pg:/apps/server/web/monitor.queue/files/queuenumber.pg
